# Numpy
- A Library
- Scientific Calculation with support for arrays and matrices
- Collection of Mathametical functions.

---

In [3]:
import numpy as np

#### 1D Array

- shape is (4,) => 1D arr, 4 are elements
---

In [6]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


#### 2D Array

---

In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [23]:
arr1 = np.array([1,2,3,4])
arr1 = arr1.reshape(1,4)
print(arr1)

[[1 2 3 4]]
