# Numpy
- A Library
- Scientific Calculation with support for arrays and matrices
- Collection of Mathametical functions.

---

In [3]:
import numpy as np

#### 1D Array

- shape is (4,) => 1D arr, 4 are elements
---

In [6]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


#### 2D Array

---

In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [23]:
arr1 = np.array([1,2,3,4])
arr1 = arr1.reshape(1,4)
print(arr1)

[[1 2 3 4]]


---
#### Inbuilt functions

1. `arrange()`: usefull
2. `ones()`: in DL
3. `eye()`: identity metrix
---

In [42]:
print(np.arange(0,10,2).reshape(5,1),"\n")
print(np.ones((5,5)),"\n")
print(np.eye(4))

[[0]
 [2]
 [4]
 [6]
 [8]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
#### Summary & Other function

---


In [47]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array: ",arr3,"\n")
print("Shape:",arr3.shape,"\n")
print("Dimension:",arr3.ndim,"\n")
print("|element|:",arr3.size,"\n")
print("Data Types:",arr3.dtype,"\n")
print("Element size in bytes: ",arr3.itemsize,"\n")

Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Shape: (3, 3) 

Dimension: 2 

|element|: 9 

Data Types: int64 

Element size in bytes:  8 



---
#### Numpy Vectorized Operations
---

In [ ]:
# similarly for sub, mul, div

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ", arr1 + arr2)

Addition:  [11 22 33 44 55]


---
#### Numpy Universal Functions

- `sqrt()`: sqr root
- `exp()` : Exponential, e^element
- `sin()` : sine
- `log()` : natural log
---

In [60]:
arr1 = np.array([2,3,4,5,6])

print(np.sqrt(arr1),"\n")
print(np.exp(arr1),"\n")
print(np.sin(arr1),"\n")
print(np.log(arr1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974] 

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349] 

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ] 

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


---
#### Access & Modify Elements

1. NumPy slicing follows: [start : stop]
---

In [89]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr,"\n")
print(arr[1:2,2:4],"\n")
arr[0,0]=500
arr[1:] = 1000

print(arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[7 8]] 

[[ 500    2    3    4]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]]
